name: OIDC Smoke Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Quem eu sou?
        run: aws sts get-caller-identity

      - name: Consigo ver meu repositório ECR?
        run: aws ecr describe-repositories --repository-names node-order-service